### ISSUE TITLE
plugin failed to run: syntax error

### ISSUE THREAD

**Issue by theambient** [Strider-CD/strider-docker-runner#28] opened 2015-02-10 11:38 UTC
evaluating strider. run test using docker runner and job hangs.

in strider logs i found following

```
2015-02-10T11:34:52.481Z - info: [runner:docker] Queued new job. Project: mc/auth-service Job ID: 54d9ecdcf5a4c7570ebe712b
2015-02-10T11:34:52.538Z - info: [runner:docker] Job started. Project: mc/auth-service Job ID: 54d9ecdcf5a4c7570ebe712b
2015-02-10T11:34:52.545Z - info: [runner:docker] Found a disabled plugin: node Project: mc/auth-service Job ID: 54d9ecdcf5a4c7570ebe712b

/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/dockerode-optionator/index.js:7
    var host = options.host || env.DOCKER_IP;
                      ^
TypeError: Cannot read property 'host' of undefined
    at Object.module.exports.normalizeOptions (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/dockerode-optionator/index.js:7:23)
    at module.exports (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/lib/init.js:5:28)
    at Object.module.exports [as processJob] (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/lib/run.js:7:3)
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/lib/index.js:345:21
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/lib/index.js:264:7
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:190:13
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:94:25
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:187:17
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:459:34
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/lib/index.js:254:15
    at handler (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/lib/index.js:28:10)
    at module.exports.init (/usr/local/lib/node_modules/strider/node_modules/strider-custom/worker.js:7:5)
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/lib/index.js:256:30
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:454:21
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:185:13
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-simple-runner/node_modules/async/lib/async.js:86:13
```

**Comment by knownasilya** [comment] 2015-02-10 12:48
Have you configured the docker runner for your branch? It seems from the error like you haven't.

Also, the error could be better, or it could use some defaults. Thoughts @keyvanfatehi?

**Comment by keyvanfatehi** [comment] 2015-02-10 13:40
@knownasilya Most likely he has not configured it, but we should handle this gracefully so that the better errors can come through which advise how to configure via env vars, etc.

**Comment by theambient** [comment] 2015-02-10 13:41
How can I configure It?

I tried `export DOCKER_HOST="unix:///var/run/docker.sock"` but it didn't help

**Comment by keyvanfatehi** [comment] 2015-02-10 13:48
I just replicated the error -- you can get past that particular error by going to /org/project/config/runner-docker and clicking "save", (PR #29 would make this unnecessary) but now I see there are some more issues which I had not seen before and will need to investigate... these errors are just crashing the process and not propagating back up to the UI like they're supposed to anymore...

**Comment by keyvanfatehi** [comment] 2015-02-10 14:31
@theambient I've just patched the plugin -- it should not crash and should give you better errors now that will to help you see misconfiguration.

As far as how to configure, you can set some stuff in the web interface, but it's better to use the standard docker environment variables. for example on my dev machine I am using boot2docker, which sets the following for me:

```
DOCKER_CERT_PATH=/Users/keyvan/.boot2docker/certs/boot2docker-vm
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
```

this is picked up and handled correctly by strider and the docker runner v 1.3.1 (just released now)

closing this issue but please reopen if the problem is not fixed

**Closed by keyvanfatehi** 2015-02-10 14:31 UTC

**Comment by keyvanfatehi** [comment] 2015-02-10 14:35
@theambient I should also advice you explicitly on DOCKER_HOST for your setup. export DOCKER_HOST="unix:///var/run/docker.sock" should work just fine.

**Comment by theambient** [comment] 2015-02-10 15:17
thanks guys. works. just updated plugin.

btw, i encounter next error =)

```
git clone --recursive XYZ . -b master git 7.2s -1
Cloning into '.'...
Submodule 'XXX'
Cloning into 'XXX'...
Submodule path 'XXX': checked out 'c60603bea3f1e1384f191d6f01029c2fcd3b890c'
$ git checkout -qf master git 27ms -1
fatal: Not a git repository (or any of the parent directories): .git
$  -1
An unexpected error occurred while executing this job. Please report at https://github.com/Strider-CD/strider/issues

Checkout failed with code 128

Error: Checkout failed with code 128
    at badCode (/usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:88:11)
    at /usr/local/lib/node_modules/strider/node_modules/strider-git/worker.js:119:22
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/strider-runner-core/lib/job.js:203:9)
    at EventEmitter.emit (events.js:95:17)
    at /usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/lib/create-container.js:108:18
    at Stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:192:22)
    at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at Stream.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/index.js:242:12)
    at Stream.stream.write (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at drain (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/through/index.js:45:5)
    at emit (/usr/local/lib/node_modules/strider/node_modules/strider-docker-runner/node_modules/event-stream/node_modules/split/index.js:36:14)
```
